### ISSUE TITLE
Unit tests and CI (GitHub actions)

### ISSUE THREAD

**Issue by kokitsuyuzaki** [rikenbit/dcTensor#6]
@dekuenstle 's comment

> Unit tests are available in the repository, but test coverage and automation are not documented.

> The Github action workflow "build_test_push.yml", running on push and pull, apparently is not
running the test suite–––Test automation should be added or, if already done, documented.

**Comment by kokitsuyuzaki** [comment]
Dear, @dekuenstle

Sorry, do you mean "documented" as writing description to which file?
I think README.md is information to users and developers, and whether the source code is tested or not is not so much information they want to know.
Or do you mean that I should simply explain it in this issue tracker?

**Comment by dekuenstle** [comment]
I think there are multiple options to document you testing scheme. In the developer instructions, you could add a line about where to add unit tests and how to run them. Additionally, many repos provide a batch that visualizes the test status and coverage. In any case, I recommend to run the unit tests automatically.

**Comment by kokitsuyuzaki** [comment]
> automation

> documented

Unit tests have already been automated.

In the GitHub Actions,
```.github/workflows/build_test_push.yml``` is parsed,
and then ```Dockerfile``` is performed.

In the ```Dockerfile```, 
```tools::testInstalledPackage``` function is performed in R language,
and all the test codes in ```tests/``` are performed.
https://github.com/rikenbit/dcTensor/blob/bf5b298860daa42e999f52820243e125fdb38193/Dockerfile#L7

Note that collecting test scripts under ```tests/``` is a convention among R package developers and is the specification of ```testthat```, which is the most widely used unit test support package, so no explanation is needed.

**Comment by kokitsuyuzaki** [comment]
> test coverage

Test codes are as follows:
https://github.com/rikenbit/dcTensor/blob/bf5b298860daa42e999f52820243e125fdb38193/tests/testthat.R#L8-L52

The codes are fully covered all the functions but I dared to comment out most of the tests here.
This is because the CRAN repository said that it is not good to take too much time for testing.

The results of the coverage calculation with the ```covr``` package, with everything uncommented out, are as follows.

```
> library("covr")
> cov <- package_coverage()
> print(cov)

dcTensor Coverage: 76.82%
R/toyModel.R: 3.60%
R/dcTensor-internal.R: 49.50%
R/dSVD.R: 82.03%
R/dNMF.R: 83.73%
R/djNMF.R: 84.58%
R/dsiNMF.R: 85.02%
R/dPLS.R: 85.06%
R/dNTD.R: 85.92%
R/dNTF.R: 88.14%
```

However, I think there is a bug in the ```covr``` package itself; it tends to ignore hidden functions.
This is found in previous JOSS submission of ```iTensor``` package.
https://github.com/rikenbit/iTensor/issues/4

In fact ```covr``` estimates a low percentage (3.60%) even though all functions of ```R/toyModel.R``` are called in ```tests/test_toyModel.R```.
Therefore, this result should be used only as a reference.

**Comment by dekuenstle** [comment]
> In the GitHub Actions, `.github/workflows/build_test_push.yml` is parsed, and then `Dockerfile` is performed.
> In the `Dockerfile`, `tools::testInstalledPackage` function is performed in R language, and all the test codes in `tests/` are performed.

Great that you already run the tests! However, I think, this is not obvious for anyone looking at your repository. It might be helpful if you a) would add a small text to your developer instructions, explaining what happens in the github action and b) add a comment in the github action, stating what is happening on this single command that runs the dockerfile. 


> The codes are fully covered all the functions but I dared to comment out most of the tests here.
> This is because the CRAN repository said that it is not good to take too much time for testing.

Would it be possible to separate fast and slow tests? Then  you could run tiny & fast tests automatically for each function to assert a working API   (e.g., on every pull request & release). The tests that take too long for CRAN could be manually triggered e.g. by the developer (needs some documentation then). 

The R package `testthat` provides specific functionality to [skip tests](https://testthat.r-lib.org/articles/skipping.html):


> [skip_on_cran()](https://testthat.r-lib.org/reference/skip.html) skips tests on CRAN. This is useful for slow tests and tests that occasionally fail for reasons outside of your control.
>
> [skip_on_os()](https://testthat.r-lib.org/reference/skip.html) allows you to skip tests on a specific operating system. Generally, you should strive to avoid this as much as possible (so your code works the same on all platforms), but sometimes it’s just not possible.
>
>  [skip_on_ci()](https://testthat.r-lib.org/reference/skip.html) skips tests on most continuous integration platforms (e.g. GitHub Actions, Travis, Appveyor).

**Comment by kokitsuyuzaki** [comment]
I can't imagine writing how to test codes in the README.
I couldn't find such README on GitHub for now.
cf. https://github.com/tidyverse/tidyverse

Do you have some good examples?

**Comment by dekuenstle** [comment]
Many packages have contributor instructions explaining how to specify and run tests. This contributor guide *can* be part of the readme or completely separate. e.g., ggplot2 explained their usage of tests on their homepage: https://ggplot2.tidyverse.org/CONTRIBUTING.html

**Comment by kokitsuyuzaki** [comment]
Thanks, it looks good.

Then, refering ggplot2's document, I will add a description how to test codes, if others participate in the development of dcTensor, in the CONTRIBUTING section.
https://github.com/rikenbit/dcTensor#contributing

**Comment by kokitsuyuzaki** [comment]
I tried `skip_on_cran` all day today.

It seems that the test that `skip_on_cran` is written skipped,
when the environment variable `NOT_CRAN` is "true".
It seems that this value is assumed to be "skip" on CRAN and "true" on the other environment.
(There is no way to check the value of the environment variable on CRAN though...)

However, in my environment, `NOT_CRAN` has no value (""),
and when I perform all the tests in this state,
they will be mistakenly assumed to be on CRAN,
and as a result, the tests with `skip_on_cran` were skipped, as shown below.

```
...
── Skip ('test_dPLS.R:2:2'): dPLS ──────────────────────────────────────────────
Reason: On CRAN

[ FAIL 0 | WARN 0 | SKIP 1 | PASS 0 ]
[ FAIL 0 | WARN 0 | SKIP 1 | PASS 0 ]

── Skip ('test_dNTF.R:2:2'): dNTF ──────────────────────────────────────────────
Reason: On CRAN
...
```

Conversely, when explicitly executed with `NOT_CRAN`="true" as shown below, I could confirm that the tests are indeed executed even if `skip_on_cran` is written in the tests.

```
Sys.setenv(NOT_CRAN="true")
```

However, if I write this, I expect that all the tests will run on CRAN.

As mentioned above, `skip_on_cran` has a suspicious behavior, and I found it easier for me to operate my packages with simple comment-outs.

**Comment by dekuenstle** [comment]
In the end, it is your decision how you like to run the tests in this repository. I prefer to automate as much as possible (in this case, run all tests on the Github Action but only a subset on CRAN) to minimize the chance of human mistakes. However, manual steps like setting a flag or commenting out to test the software are not necessarily a show-stopper for JOSS. At least, if these manual steps are well documented  (see the [review guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#tests))

**Comment by kokitsuyuzaki** [comment]
Thanks for letting me know.
The `skip_on_cran` has little well written documentation on how to use it, and I am not confident that I can properly use it, so I will comment it out this time.

I have added a note to `CONTRIBUTING.md` regarding how to run the test and commenting it out.
https://github.com/rikenbit/dcTensor/commit/9c26b15d6b306db5a7bbc536a816b0b37aa9a879#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055
